#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

files=$(git diff --name-only --cached)

if [ ! -z "$files" ]; then
  npx eslint $files --fix
  npx prettier --write $files --ignore-unknown
  git add $files
fi